export const ACTION_AUTHENTICATE = "ACTION_AUTHENTICATE"
export const ACTION_SYNC = "ACTION_SYNC"
export const ACTION_DISCONNECT = "ACTION_DISCONNECT"
export const ACTION_UPGRADE_FIRMWARE = "ACTION_UPGRADE_FIRMWARE"