package io.github.aidenkoog.note_memo_app.ui.theme

import androidx.compose.ui.graphics.Color

val DarkGray = Color(0xFF202020)
val LightGreen = Color(0xFFB7EECE)

//Light
val md_theme_light_primary = Color(0xFF70DBA7)
val md_theme_light_onPrimary = Color(0xFF003823)
val md_theme_light_primaryContainer = Color(0xFF8DF7C2)
val md_theme_light_onPrimaryContainer = Color(0xFF002113)
val md_theme_light_secondary = Color(0xFF006D34)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF76FD9C)
val md_theme_light_onSecondaryContainer = Color(0xFF00210B)
val md_theme_light_tertiary = Color(0xFF006D3E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF58FFA5)
val md_theme_light_onTertiaryContainer = Color(0xFF00210F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DD)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)
val md_theme_light_outline = Color(0xFF707972)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF70DBA7)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006C48)
val md_theme_light_outlineVariant = Color(0xFFC0C9C1)
val md_theme_light_scrim = Color(0xFF000000)

//Dark
val md_theme_dark_primary = Color(0xFF70DBA7)
val md_theme_dark_onPrimary = Color(0xFF003823)
val md_theme_dark_primaryContainer = Color(0xFF005235)
val md_theme_dark_onPrimaryContainer = Color(0xFF8DF7C2)
val md_theme_dark_secondary = Color(0xFF57DF82)
val md_theme_dark_onSecondary = Color(0xFF003918)
val md_theme_dark_secondaryContainer = Color(0xFF005225)
val md_theme_dark_onSecondaryContainer = Color(0xFF76FD9C)
val md_theme_dark_tertiary = Color(0xFF2DE28B)
val md_theme_dark_onTertiary = Color(0xFF00391E)
val md_theme_dark_tertiaryContainer = Color(0xFF00522E)
val md_theme_dark_onTertiaryContainer = Color(0xFF58FFA5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C1)
val md_theme_dark_outline = Color(0xFF8A938C)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF006C48)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF70DBA7)
val md_theme_dark_outlineVariant = Color(0xFF404943)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFB7EECE)

val ImperialRed = Color(0xFFF21E36)
val Verdigris = Color(0xFF5DDBBC)
val GoldMetallic = Color(0xFFFFE025)
val MildGreen = Color(0xFF15E28F)
val LightOrange = Color(0xFFFFB963)


